config/routes.rb
Rails.application.routes.draw do

get 'events/create'
get 'comments/create'

root 'sessions#new'

get '/users' => 'users#index', as: :users
get '/users/new' => 'users#new', as: :new_users
get 'users/:id/events' => 'users#show', as: :user
post '/users' => 'users#create'
get '/users/:id/edit' => 'users#edit', as: :edit_user
patch '/users/:id' => 'users#update'
delete '/users/:id' => 'users#destroy'

get '/events' => 'events#index', as: :events
get '/events/new' => 'events#new', as: :new_events
get '/events/:id' => 'events#show', as: :event
post '/events/new' => 'events#create'
patch '/events/:id' => 'events#update'
get '/events/:id/edit' => 'events#edit', as: :event_edit
delete '/events/:id' => 'events#destroy'

get '/events/:id/comments' => 'comments#index', as: :event_comments
get '/events/:id/comments/new' => 'comments#new', as: :event_comment_new
delete '/events/:id/comments' => 'comments#destroy', as: :event_comment_destroy
post 'events/:id/comments' => 'comments#create'

get '/login' => 'sessions#new', as: :login
post '/login' => 'sessions#create'
delete '/logout' => 'sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  # has_many :comments
  has_many :comments, through: :events

  has_secure_password
  # Verify that an email exists and that it does not already exist in the db
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in, :authorize

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in
  !!current_user

  end

  def authorize
    redirect_to login_path unless logged_in

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Event.find(params[:event_id]).comments
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def create
    @event = Event.find(params[:id])
    @event.comments.create({
      body: params[:comment][:body],
      user_id: current_user.id
    })
    redirect_to event_path(@event)
  end

  def edit

  end

  def update
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to event_path(@comment.event)
  end

  def comments_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authorize, only: [:new]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
  end

  def new
    @event = Event.new

  end

  def create
    @event = Event.new({name: params[:event][:name],
      date: params[:event][:date],
      location: params[:event][:location],
      pic_url: params[:event][:pic_url]
      })
      @event.user = current_user
      if @event.save
        redirect_to user_path(current_user)
      else
        redirect_to new_users_path

      end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to event_path
    else
      redirect_to edit_event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if current_user == @event.user
      @event.destroy
    end
    redirect_to user_path(current_user)
  end
  def event_params
    params.require(:event).permit(:name, :date, :location, :pic_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # first try and find user by email in db
    @user = User.find_by_email(params[:login][:email])
    # if the user exists AND they put in the right password:
    if @user && @user.authenticate(params[:login][:password])
      #generate a cookie for the user
      session[:user_id] = @user.id
      
      redirect_to user_path(@user)
    else
      #redirect them back to the login page
      redirect_to login_path
    end
  end

  def destroy
    # delete that key/value pair in our sessions hash
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
@users = User.all

  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
    @event = Event.new

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path @user.id
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      redirect_to edit_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to user_path
    else redirect_to edit_user_path
  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
  @current_user ||= User.find_by(id: session[:user_id])
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Say Something</h1>
<%= form_for @comments do |f|%>
<%= f.text_area :body, placeholder: "Say Something Here" %>
<%= f.submit %>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments/<h1>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Say Something</h1>
    <%= form_for @comment, url: event_comments_path do |f|%>
    <%= f.text_area :body, placeholder: "Say Something Here" %>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Update Event</h1>
<%= form_for @event do |f| %><br>
  <%= f.text_field :name, placeholder: "Event Name" %><br>
  <%= f.date_field :date, placeholder: "..." %><br>
  <%= f.text_field :location, placeholder: "Location" %><br>
  <%= f.url_field :pic_url, placeholder: "photos" %><br><br>
  <%= f.submit %><br>
<% end %>

app/views/events/index.html.erb
<h1>Events#index</h1>
<ul>
  <% @events.each do |e| %>
    <li><%= link_to e.name, event_path(e) %></li>
  <% end %>
</ul>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New Event</h1>
    <%= form_for @event, url: new_events_path do |f|%><br>
    <%= f.text_field :name, placeholder: "Event Name" %><br>
    <%= f.date_field :date, placeholder: "..." %><br>
    <%= f.text_field :location, placeholder: "Location" %><br>
    <%= f.url_field :pic_url, placeholder: "photos" %><br>
    <%= f.submit %><br>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= @event.name %></h1><br>
    <%= @event.date.strftime("%A, %b %d, %Y") %><br>

    <%= @event.location %><br>
    <%= image_tag @event.pic_url, width: "700px" %><br>
    <% if @event.user == current_user %>
      <%= link_to "Edit", event_edit_path(@event) %>
      <%= link_to "Delete", event_path(@event), {method: :delete} %>
    <% end %>

    <br>

    <h4>Say Something</h4>
    <%= form_for [@event, @comment] do |f| %>
    <div>
      <%= f.text_area :body, placeholder: "Say Something Here" %>
    </div>
    <div>
      <%= f.submit %>
    </div>
    <% end %>

    <% @event.comments.each do |comment| %>
      <li>
        <blockquote>
          <%= comment.body %><br>
          <%= time_ago_in_words comment.created_at %><br><br>
        </blockquote>
        <% if comment.user_id == session[:user_id] %>
          <%= link_to "Delete", event_comments_path(comment), {method: :delete} %>
        <% end %>
      </li>
    <% end %>
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">EventBook</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
        <li><%= link_to 'My Events', user_path(current_user) %></li>
          <% end %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
              <li><a><%= current_user.name %></a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign Up', new_users_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBookApp</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>EventBook</h1>
    <ul>
      <% %>
      <!-- <% @users.each do |u| %>
      <li><%= link_to u.name, user_path(u) %></li>
      <% end %> -->

    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <div>
        <%= f.text_field :name, placeholder: "name" %>

        <%= f.email_field :email, placeholder: "email" %>

        <%= f.password_field :password, placeholder: "password" %>

        <%= f.password_field :password_confirmation, placeholder: "confirm password" %>

        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= @user.name %></h1>
    <h2><%= link_to 'Add an Event', new_events_path %></h2>

    <ul>
      <% @user.events.each do |e| %>
        <li><%= link_to e.name, event_path(e) %></li>
          <% end %>
    </ul>  
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>